version: 2

defaults: &defaults
  working_directory: ~/project/react-mentions
  docker:
    - image: circleci/node:8-browsers
      environment:
        CHROME_BIN: "/usr/bin/google-chrome"

attach_workspace: &attach_workspace
  attach_workspace:
      at: ~/project

restore_cache: &restore_cache
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v1-node-{{ .Branch }}-
      - v1-node-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - *restore_cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn cache
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -r node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - react-mentions

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Test
          command: yarn test:coverage
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

  publish-demo:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - add_ssh_keys:
          fingerprints:
            - "21:90:d1:2d:be:19:c0:20:da:80:8a:6f:78:78:1f:91"
      - run:
          name: Fix host authenticity for github.com
          command: mkdir -p ~/.ssh/ && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set git name & email
          command: |
            git config --global user.name "CircleCI" && git config --global user.email "circleci@signavio.com"
      - run:
          name: Build demo
          command: yarn build-demo
      - run:
          name: Publish demo
          command: yarn publish-demo

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Release
          command: yarn semantic-release



workflows:
  version: 2
  qa-publish-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - publish-demo:
          requires:
            - install
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
